#!/usr/bin/env python3
"""Render the on-demand human tasks view from canonical PLAN/RUN state.

`tasks.md` is a non-canonical human view: `RUN.md`'s JSON manifest stays the
only coordination authority. This command reads a validated PLAN/RUN pair and
renders one deterministic Markdown listing grouped by mission — newest mission
first, so plan revisions that append missions surface at the top and M1 sits at
the bottom — so a human can see which tasks each mission carries and where the
run currently stands without reading JSON. It writes no canonical state,
refuses a pair whose plan revision/digest no longer matches, and refuses to
overwrite a file it did not generate itself.

The view ends with a hand-maintained `## Update Log` section fenced by
`update-log` markers: the renderer rewrites everything above the markers and
preserves the fenced inner text verbatim on every re-render, so post-run
update rows survive regeneration. `--check` compares only the generated part;
editing the log never marks the view stale.
"""

from __future__ import annotations

import argparse
import json
import os
import sys
from collections.abc import Callable
from pathlib import Path
from typing import Any

from harness_core import mission_dependencies, extract_json_manifest_text
from harness_manifest import (
    ManifestError,
    load_plan,
    load_run,
    validate_current_plan_run,
)

GENERATED_MARKER = "<!-- generated by scripts/render_tasks_view.py -->"
UPDATE_LOG_START = "<!-- update-log:start -->"
UPDATE_LOG_END = "<!-- update-log:end -->"

LIVE_MISSION_PHASES = {
    "ready",
    "leased",
    "worker_running",
    "worker_passed",
    "integrating",
}
STALLED_MISSION_PHASES = {
    "blocked",
    "worker_failed",
    "integration_failed",
}
RECORDED_TASK_PHASE = "mission_recorded"

TASK_TABLE_HEADER = (
    "| Task | Objective | Depends on | Phase | Verifier | Attempts | Commit |\n"
    "|---|---|---|---|---|---|---|"
)


def _cell(text: Any) -> str:
    """Make one single-line, pipe-safe Markdown table cell."""
    if text is None:
        return ""
    line = " ".join(str(text).split())
    return line.replace("|", "\\|")


def _short_sha(value: Any) -> str:
    if isinstance(value, str) and len(value) >= 12:
        return f"`{value[:12]}`"
    return _cell(value)


def _list_or_none(values: Any) -> str:
    if not isinstance(values, list) or not values:
        return "none"
    return ", ".join(_cell(value) for value in values)


def _blockers(state: dict[str, Any]) -> str:
    blockers = state.get("blockers")
    if not isinstance(blockers, list) or not blockers:
        return ""
    rendered = "; ".join(
        blocker if isinstance(blocker, str)
        else json.dumps(blocker, sort_keys=True)
        for blocker in blockers
    )
    return f" · blockers: {_cell(rendered)}"


def _counts(plan: dict[str, Any], run: dict[str, Any]) -> tuple[int, int, int, int]:
    missions = [item for item in plan.get("missions", []) if isinstance(item, dict)]
    mission_states = run.get("mission_states", {})
    integrated = sum(
        1
        for mission in missions
        if isinstance(mission_states.get(mission.get("id")), dict)
        and mission_states[mission["id"]].get("phase") == "integrated"
    )
    tasks = [
        task
        for mission in missions
        for task in (mission.get("tasks") or [])
        if isinstance(task, dict)
    ]
    task_states = run.get("task_states", {})
    recorded = sum(
        1
        for task in tasks
        if isinstance(task_states.get(task.get("id")), dict)
        and task_states[task["id"]].get("phase") == RECORDED_TASK_PHASE
    )
    return integrated, len(missions), recorded, len(tasks)


def _frontier(plan: dict[str, Any], run: dict[str, Any]) -> str:
    mission_states = run.get("mission_states", {})
    live: list[str] = []
    next_queued: list[str] = []
    for mission in plan.get("missions", []):
        if not isinstance(mission, dict):
            continue
        mission_id = mission.get("id")
        state = mission_states.get(mission_id)
        phase = state.get("phase") if isinstance(state, dict) else None
        if phase in LIVE_MISSION_PHASES or phase in STALLED_MISSION_PHASES:
            live.append(f"{mission_id} ({phase})")
        elif phase != "integrated":
            next_queued.append(f"next: {mission_id} ({phase})")
    if live:
        return ", ".join(live)
    if next_queued:
        return next_queued[0]
    return "none — every mission integrated"


def _mission_section(
    mission: dict[str, Any],
    plan: dict[str, Any],
    run: dict[str, Any],
    dependencies: dict[str, list[str]],
) -> str:
    mission_id = mission["id"]
    state = run.get("mission_states", {}).get(mission_id, {})
    phase = state.get("phase", "unknown") if isinstance(state, dict) else "unknown"

    lines = ["", f"## {_cell(mission_id)}"]
    alias = mission.get("alias")
    if isinstance(alias, str) and alias.strip():
        lines[1] += f" — {_cell(alias)}"
    lines.append("")
    lines.append(f"Objective: {_cell(mission.get('objective'))}")
    lines.append("")

    summary = f"Phase: {phase}"
    depends_on = dependencies.get(mission_id) or []
    summary += f" · depends on: {_list_or_none(depends_on)}"
    if isinstance(state, dict):
        if isinstance(state.get("integrated_sha"), str):
            summary += f" · integrated at {_short_sha(state['integrated_sha'])}"
        summary += _blockers(state)
    lines.append(summary)

    tasks = [task for task in (mission.get("tasks") or []) if isinstance(task, dict)]
    if not tasks:
        return "\n".join(lines)

    task_states = run.get("task_states", {})
    lines += ["", TASK_TABLE_HEADER]
    for task in tasks:
        task_state = task_states.get(task.get("id"), {})
        if not isinstance(task_state, dict):
            task_state = {}
        lines.append(
            "| {task} | {objective} | {depends_on} | {phase} | {verifier} | {attempts} | {commit} |".format(
                task=_cell(task.get("id")),
                objective=_cell(task.get("objective")),
                depends_on=_list_or_none(task.get("depends_on")),
                phase=_cell(task_state.get("phase", "unknown")),
                verifier=_cell(task_state.get("verifier_status", "unknown")),
                attempts=_cell(task_state.get("attempts", 0)),
                commit=(
                    _short_sha(task_state["commit_sha"])
                    if isinstance(task_state.get("commit_sha"), str)
                    else ""
                ),
            )
        )
    return "\n".join(lines)


def _short_digest(run: dict[str, Any]) -> str:
    digest = (run.get("plan") or {}).get("digest_sha256")
    return digest[:12] if isinstance(digest, str) and digest else "-"


def extract_update_log(existing: str) -> str:
    """Return the hand-maintained inner text between the update-log markers."""

    if UPDATE_LOG_START not in existing or UPDATE_LOG_END not in existing:
        return ""
    _, _, rest = existing.partition(UPDATE_LOG_START)
    inner, _, _ = rest.partition(UPDATE_LOG_END)
    return inner.strip("\n")


def with_update_log(view: str, inner: str = "") -> str:
    """Append the Update Log scaffold, carrying over preserved inner rows."""

    body = inner.strip("\n")
    lines = [
        "",
        "## Update Log",
        "",
        "Hand-maintained: one dated row per post-run update. The renderer",
        "preserves this section verbatim and rewrites everything above it.",
        "",
        UPDATE_LOG_START,
    ]
    if body:
        lines.append(body)
    lines.append(UPDATE_LOG_END)
    return view.rstrip("\n") + "\n" + "\n".join(lines) + "\n"


def _assert_plain_repo_path(path: Path, repo_root: Path) -> None:
    """Refuse automated writes outside the repo or through a reparse target."""

    resolved_root = repo_root.resolve(strict=True)
    resolved_path = path.resolve(strict=False)
    try:
        resolved_path.relative_to(resolved_root)
    except ValueError as exc:
        raise ValueError(f"{path} is outside repo root {repo_root}") from exc

    current = path
    while current != current.parent:
        if current.exists() and (
            current.is_symlink()
            or bool(getattr(current.stat(), "st_file_attributes", 0) & 0x0400)
        ):
            raise ValueError(f"{current} is a symlink or reparse point")
        current = current.parent


def refresh_view(
    plan: dict[str, Any],
    run: dict[str, Any],
    out: Path,
    *,
    repo_root: Path | None = None,
    check_sources: Callable[[], None] | None = None,
) -> Path:
    """Write one projection from already-validated PLAN/RUN objects.

    Checkpoint callers reuse their in-memory validated pair so refreshing the
    non-canonical view does not repeat full manifest validation. The standalone
    CLI remains the repair and check path because it reloads and validates both
    canonical files.
    """

    from harness_transition import (
        _assert_non_reparse_path,
        _open_posix_parent_chain,
        _open_windows_parent_chain,
        _replace_document_text,
    )

    out = Path(os.path.abspath(out))
    _assert_non_reparse_path(out)
    if repo_root is not None:
        _assert_plain_repo_path(out, Path(repo_root))
    view = build_view(plan, run)
    preserved = ""
    existing = None
    if out.exists():
        existing = out.read_text(encoding="utf-8")
        if GENERATED_MARKER not in existing:
            raise ValueError(
                f"refusing to overwrite non-generated tasks view {out}"
            )
        preserved = extract_update_log(existing)
    updated = with_update_log(view, preserved)
    if check_sources is not None:
        check_sources()
    if updated == existing:
        return out
    out.parent.mkdir(parents=True, exist_ok=True)
    _assert_non_reparse_path(out)
    if existing is not None:
        _replace_document_text(
            out, updated, expected_text=existing, before_commit=check_sources
        )
    else:
        # Hold the ancestor chain and create exclusively. A raced user file
        # wins; never truncate it or remove a partially written recovery file.
        posix_handles = []
        windows_handles = []
        try:
            if os.name == "nt":
                windows_handles = _open_windows_parent_chain(out.parent)
            else:
                posix_handles = _open_posix_parent_chain(out.parent)
            if check_sources is not None:
                check_sources()
            flags = os.O_WRONLY | os.O_CREAT | os.O_EXCL | getattr(os, "O_NOFOLLOW", 0)
            fd = os.open(
                out.name if posix_handles else out,
                flags,
                0o600,
                **({"dir_fd": posix_handles[-1]} if posix_handles else {}),
            )
            with os.fdopen(fd, "w", encoding="utf-8", newline="\n") as handle:
                handle.write(updated)
                handle.flush()
                os.fsync(handle.fileno())
        finally:
            for fd in reversed(posix_handles):
                os.close(fd)
            for kernel32, handle in reversed(windows_handles):
                kernel32.CloseHandle(handle)
    if check_sources is not None:
        check_sources()
    return out


def source_guard(
    plan: dict[str, Any], run: dict[str, Any], plan_path: Path, run_path: Path,
    *, expected_plan_text: str | None = None,
) -> Callable[[], None]:
    """Bind a projection to the exact saved pair without validating it again."""

    plan_text = plan_path.read_text(encoding="utf-8")
    run_text = run_path.read_text(encoding="utf-8")
    if (
        (expected_plan_text is not None and plan_text != expected_plan_text)
        or extract_json_manifest_text(
            plan_text, "## Harness Plan Manifest", "harness_plan", source=plan_path
        ) != plan
        or extract_json_manifest_text(
            run_text, "## Harness Run State", "harness_run", source=run_path
        ) != run
    ):
        raise ManifestError("PLAN/RUN changed before tasks-view refresh")

    def check() -> None:
        if (plan_path.read_text(encoding="utf-8") != plan_text
                or run_path.read_text(encoding="utf-8") != run_text):
            raise ManifestError("PLAN/RUN changed during tasks-view refresh; re-render the view")

    return check


def build_view(plan: dict[str, Any], run: dict[str, Any]) -> str:
    """Render the deterministic Markdown view from validated PLAN/RUN dicts."""
    dependencies = mission_dependencies(plan)
    integrated, mission_total, recorded, task_total = _counts(plan, run)

    lines = [
        f"# Tasks: {_cell(plan.get('objective'))}",
        "",
        GENERATED_MARKER,
        "",
        (
            f"Human view of run `{run.get('run_id')}` ({run.get('status')}) "
            f"against PLAN `{plan.get('plan_id')}` revision {plan.get('revision')}. "
            "`RUN.md` is authoritative for mission and task state: never edit "
            "the generated part of this file by hand — regenerate it with "
            "`scripts/render_tasks_view.py` after RUN.md changes; the fenced "
            "Update Log at the end is the one hand-maintained section."
        ),
        "",
        f"- Progress: {integrated}/{mission_total} missions integrated · "
        f"{recorded}/{task_total} tasks recorded",
        f"- Current frontier: {_frontier(plan, run)}",
        "- State fingerprint: plan revision "
        f"`{plan.get('revision')}` digest `{_short_digest(run)}` · graph "
        f"`{(run.get('graph_state') or {}).get('graph_revision', '-')}` · wave "
        f"`{(run.get('active_wave') or {}).get('wave_id') or '-'}`",
    ]
    for mission in reversed(plan.get("missions", [])):
        if isinstance(mission, dict) and isinstance(mission.get("id"), str):
            lines.append(_mission_section(mission, plan, run, dependencies))
    return "\n".join(lines) + "\n"


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--plan", type=Path, required=True)
    parser.add_argument("--run", type=Path, required=True)
    parser.add_argument(
        "--repo-root",
        type=Path,
        help="repository root required by current immutable PLAN/RUN validation",
    )
    parser.add_argument(
        "--out",
        type=Path,
        help=(
            "write the view here (normally docs/tasks.md); refuses to "
            "overwrite a file this tool did not generate"
        ),
    )
    parser.add_argument(
        "--check",
        action="store_true",
        help=(
            "with --out: re-render and compare; exit 1 when the file is "
            "missing, was not generated by this tool, or is stale"
        ),
    )
    return parser


def main(argv: list[str] | None = None) -> int:
    args = build_parser().parse_args(argv)
    try:
        plan = load_plan(args.plan)
        run = load_run(args.run)
        errors = validate_current_plan_run(plan, run, repo_root=args.repo_root)
        if errors:
            print(
                "PLAN/RUN pair does not validate; RUN.md is authoritative, fix it first:",
                file=sys.stderr,
            )
            for message in errors:
                print(f"  {message}", file=sys.stderr)
            return 2
        view = build_view(plan, run)
        if args.check:
            if args.out is None:
                print("--check requires --out", file=sys.stderr)
                return 2
            if not args.out.exists():
                print(f"stale: {args.out} does not exist", file=sys.stderr)
                return 1
            existing = args.out.read_text(encoding="utf-8")
            if GENERATED_MARKER not in existing:
                print(
                    f"not a generated view: {args.out} lacks the generation marker",
                    file=sys.stderr,
                )
                return 1
            expected = with_update_log(view, extract_update_log(existing))
            if existing != expected:
                print(
                    f"stale: {args.out} does not match the current PLAN/RUN state; "
                    "re-render it",
                    file=sys.stderr,
                )
                return 1
            print(f"{args.out} is current")
            return 0
        if args.out is None:
            sys.stdout.write(with_update_log(view))
            return 0
        refresh_view(
            plan, run, args.out,
            check_sources=source_guard(plan, run, args.plan, args.run),
        )
        print(f"wrote {args.out}")
    except (ManifestError, OSError, ValueError) as exc:
        print(str(exc), file=sys.stderr)
        return 2
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
