"""Copy the canonical project skills into the cross-runtime plugin bundle."""

from __future__ import annotations

import argparse
import filecmp
import shutil
import tempfile
from pathlib import Path


REPO_ROOT = Path(__file__).resolve().parents[1]
SOURCE_ROOT = REPO_ROOT / ".agents" / "skills"
DESTINATION_ROOT = REPO_ROOT / "plugins" / "fullstack-harness" / "skills"
MARKER = DESTINATION_ROOT / ".generated-from-agents-skills"
SKILL_NAMES = (
    "fullstack-harness-claude-code",
    "fullstack-harness-codex",
    "fullstack-harness-engineering",
    "fullstack-harness-github-landing",
    "prd-builder",
)


def is_link(path: Path) -> bool:
    """Return whether a path can redirect traversal outside its parent."""
    is_junction = getattr(path, "is_junction", None)
    return path.is_symlink() or (is_junction is not None and is_junction())


def included_files(root: Path) -> dict[Path, Path]:
    files: dict[Path, Path] = {}
    for path in root.rglob("*"):
        if is_link(path):
            continue
        if not path.is_file():
            continue
        if "__pycache__" in path.parts or path.suffix == ".pyc":
            continue
        files[path.relative_to(root)] = path
    return files


def managed_path_problem(path: Path, label: str) -> str | None:
    try:
        relative_path = path.relative_to(REPO_ROOT)
    except ValueError:
        return f"{label} root is outside the repository: {path}"

    candidate = REPO_ROOT
    for part in relative_path.parts:
        candidate /= part
        if is_link(candidate):
            kind = "root" if candidate == path else "ancestor"
            return f"symlinked {label} {kind}: {candidate}"

    try:
        path.resolve().relative_to(REPO_ROOT.resolve())
    except ValueError:
        return f"resolved {label} root is outside the repository: {path}"
    return None


def destination_path_problem() -> str | None:
    return managed_path_problem(DESTINATION_ROOT, "destination")


def symlink_entries(root: Path) -> list[Path]:
    if not root.exists():
        return []
    return [path.relative_to(root) for path in root.rglob("*") if is_link(path)]


def differences() -> list[str]:
    problems: list[str] = []
    destination_problem = destination_path_problem()
    if destination_problem:
        return [destination_problem]

    if is_link(MARKER):
        problems.append(f"symlink: {MARKER.name}")
    elif not MARKER.is_file():
        problems.append(f"missing: {MARKER.name}")

    if DESTINATION_ROOT.exists():
        expected_entries = {MARKER.name, *SKILL_NAMES}
        for path in sorted(DESTINATION_ROOT.iterdir()):
            if path.name not in expected_entries:
                problems.append(f"extra: {path.name}")

    if SOURCE_ROOT.exists():
        for path in sorted(SOURCE_ROOT.iterdir()):
            if path.is_dir() and path.name not in SKILL_NAMES:
                problems.append(f"unlisted source skill: {path.name}")

    for name in SKILL_NAMES:
        source = SOURCE_ROOT / name
        destination = DESTINATION_ROOT / name
        source_problem = managed_path_problem(source, "source")
        if source_problem:
            problems.append(source_problem)
            continue
        for relative in symlink_entries(source):
            problems.append(f"source symlink: {name}/{relative.as_posix()}")
        source_files = included_files(source)
        if is_link(destination):
            problems.append(f"symlink: {name}")
            destination_files = {}
        else:
            destination_files = (
                included_files(destination) if destination.exists() else {}
            )
            for relative in symlink_entries(destination):
                problems.append(f"symlink: {name}/{relative.as_posix()}")
                destination_files.pop(relative, None)

        for relative in sorted(source_files.keys() - destination_files.keys()):
            problems.append(f"missing: {name}/{relative.as_posix()}")
        for relative in sorted(destination_files.keys() - source_files.keys()):
            problems.append(f"extra: {name}/{relative.as_posix()}")
        for relative in sorted(source_files.keys() & destination_files.keys()):
            if not filecmp.cmp(
                source_files[relative], destination_files[relative], shallow=False
            ):
                problems.append(f"changed: {name}/{relative.as_posix()}")
    return problems


def write_marker() -> None:
    if is_link(MARKER):
        raise SystemExit(f"Refusing to use symlinked marker: {MARKER}")

    temporary_path: Path | None = None
    try:
        with tempfile.NamedTemporaryFile(
            "w",
            dir=DESTINATION_ROOT,
            prefix=f"{MARKER.name}.",
            encoding="utf-8",
            delete=False,
        ) as temporary:
            temporary.write(
                "Generated by scripts/sync_plugin_skills.py. "
                "Do not edit files in this directory directly.\n"
            )
            temporary_path = Path(temporary.name)
        temporary_path.replace(MARKER)
    finally:
        if temporary_path is not None:
            temporary_path.unlink(missing_ok=True)


def sync() -> None:
    destination_problem = destination_path_problem()
    if destination_problem:
        raise SystemExit(f"Refusing to use {destination_problem}")
    if is_link(MARKER):
        raise SystemExit(f"Refusing to use symlinked marker: {MARKER}")
    if DESTINATION_ROOT.exists() and any(DESTINATION_ROOT.iterdir()) and not MARKER.exists():
        raise SystemExit(
            f"Refusing to overwrite unmanaged files under {DESTINATION_ROOT}."
        )

    sources: dict[str, Path] = {}
    for name in SKILL_NAMES:
        source = SOURCE_ROOT / name
        source_problem = managed_path_problem(source, "source")
        if source_problem:
            raise SystemExit(f"Refusing to use {source_problem}")
        if not (source / "SKILL.md").is_file():
            raise SystemExit(f"Canonical skill is missing: {source}")
        source_symlinks = symlink_entries(source)
        if source_symlinks:
            paths = ", ".join(path.as_posix() for path in source_symlinks)
            raise SystemExit(f"Canonical skill contains symlinks: {name}: {paths}")
        sources[name] = source

    DESTINATION_ROOT.mkdir(parents=True, exist_ok=True)
    write_marker()
    managed_root = DESTINATION_ROOT.resolve()
    expected_entries = {MARKER.name, *SKILL_NAMES}
    for path in DESTINATION_ROOT.iterdir():
        if path.name in expected_entries:
            continue
        if is_link(path):
            raise SystemExit(f"Refusing to remove symlinked path: {path}")
        if path.resolve().parent != managed_root:
            raise SystemExit(f"Refusing to remove path outside {DESTINATION_ROOT}.")
        if path.is_dir():
            shutil.rmtree(path)
        else:
            path.unlink()

    for name, source in sources.items():
        destination = DESTINATION_ROOT / name
        if is_link(destination):
            raise SystemExit(f"Refusing to remove symlinked path: {destination}")
        if destination.exists():
            if destination.resolve().parent != managed_root:
                raise SystemExit(f"Refusing to remove path outside {DESTINATION_ROOT}.")
            shutil.rmtree(destination)
        shutil.copytree(
            source,
            destination,
            ignore=shutil.ignore_patterns("__pycache__", "*.py[cod]"),
        )

    problems = differences()
    if problems:
        raise SystemExit("Plugin bundle still differs:\n" + "\n".join(problems))


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "--check", action="store_true", help="Check for drift without copying files."
    )
    args = parser.parse_args()

    if args.check:
        problems = differences()
        if problems:
            raise SystemExit("Plugin bundle differs:\n" + "\n".join(problems))
        print("Plugin skill bundle matches the canonical skills.")
        return

    sync()
    print("Plugin skill bundle updated from .agents/skills.")


if __name__ == "__main__":
    main()
