"""Copy the canonical project skills into the cross-runtime plugin bundle."""

from __future__ import annotations

import argparse
import filecmp
import shutil
import tempfile
from pathlib import Path


REPO_ROOT = Path(__file__).resolve().parents[1]
SOURCE_ROOT = REPO_ROOT / ".agents" / "skills"
DESTINATION_ROOT = REPO_ROOT / "plugins" / "fullstack-harness" / "skills"
MARKER = DESTINATION_ROOT / ".generated-from-agents-skills"
SKILL_NAMES = (
    "design-package-builder",
    "fullstack-harness-engineering",
    "prd-builder",
)


def included_files(root: Path) -> dict[Path, Path]:
    files: dict[Path, Path] = {}
    for path in root.rglob("*"):
        if not path.is_file():
            continue
        if "__pycache__" in path.parts or path.suffix == ".pyc":
            continue
        files[path.relative_to(root)] = path
    return files


def destination_path_problem() -> str | None:
    try:
        relative_destination = DESTINATION_ROOT.relative_to(REPO_ROOT)
    except ValueError:
        return f"destination root is outside the repository: {DESTINATION_ROOT}"

    candidate = REPO_ROOT
    for part in relative_destination.parts:
        candidate /= part
        if candidate.is_symlink():
            kind = "root" if candidate == DESTINATION_ROOT else "ancestor"
            return f"symlinked destination {kind}: {candidate}"

    try:
        DESTINATION_ROOT.resolve().relative_to(REPO_ROOT.resolve())
    except ValueError:
        return f"resolved destination root is outside the repository: {DESTINATION_ROOT}"
    return None


def symlink_entries(root: Path) -> list[Path]:
    if not root.exists():
        return []
    return [path.relative_to(root) for path in root.rglob("*") if path.is_symlink()]


def differences() -> list[str]:
    problems: list[str] = []
    destination_problem = destination_path_problem()
    if destination_problem:
        return [destination_problem]

    if MARKER.is_symlink():
        problems.append(f"symlink: {MARKER.name}")
    elif not MARKER.is_file():
        problems.append(f"missing: {MARKER.name}")

    if DESTINATION_ROOT.exists():
        expected_entries = {MARKER.name, *SKILL_NAMES}
        for path in sorted(DESTINATION_ROOT.iterdir()):
            if path.name not in expected_entries:
                problems.append(f"extra: {path.name}")

    for name in SKILL_NAMES:
        source = SOURCE_ROOT / name
        destination = DESTINATION_ROOT / name
        source_files = included_files(source)
        if destination.is_symlink():
            problems.append(f"symlink: {name}")
            destination_files = {}
        else:
            destination_files = (
                included_files(destination) if destination.exists() else {}
            )
            for relative in symlink_entries(destination):
                problems.append(f"symlink: {name}/{relative.as_posix()}")
                destination_files.pop(relative, None)

        for relative in sorted(source_files.keys() - destination_files.keys()):
            problems.append(f"missing: {name}/{relative.as_posix()}")
        for relative in sorted(destination_files.keys() - source_files.keys()):
            problems.append(f"extra: {name}/{relative.as_posix()}")
        for relative in sorted(source_files.keys() & destination_files.keys()):
            if not filecmp.cmp(
                source_files[relative], destination_files[relative], shallow=False
            ):
                problems.append(f"changed: {name}/{relative.as_posix()}")
    return problems


def write_marker() -> None:
    if MARKER.is_symlink():
        raise SystemExit(f"Refusing to use symlinked marker: {MARKER}")

    temporary_path: Path | None = None
    try:
        with tempfile.NamedTemporaryFile(
            "w",
            dir=DESTINATION_ROOT,
            prefix=f"{MARKER.name}.",
            encoding="utf-8",
            delete=False,
        ) as temporary:
            temporary.write(
                "Generated by scripts/sync_plugin_skills.py. "
                "Do not edit files in this directory directly.\n"
            )
            temporary_path = Path(temporary.name)
        temporary_path.replace(MARKER)
    finally:
        if temporary_path is not None:
            temporary_path.unlink(missing_ok=True)


def sync() -> None:
    destination_problem = destination_path_problem()
    if destination_problem:
        raise SystemExit(f"Refusing to use {destination_problem}")
    if MARKER.is_symlink():
        raise SystemExit(f"Refusing to use symlinked marker: {MARKER}")
    if DESTINATION_ROOT.exists() and any(DESTINATION_ROOT.iterdir()) and not MARKER.exists():
        raise SystemExit(
            f"Refusing to overwrite unmanaged files under {DESTINATION_ROOT}."
        )

    sources: dict[str, Path] = {}
    for name in SKILL_NAMES:
        source = SOURCE_ROOT / name
        if not (source / "SKILL.md").is_file():
            raise SystemExit(f"Canonical skill is missing: {source}")
        sources[name] = source

    DESTINATION_ROOT.mkdir(parents=True, exist_ok=True)
    write_marker()
    managed_root = DESTINATION_ROOT.resolve()
    expected_entries = {MARKER.name, *SKILL_NAMES}
    for path in DESTINATION_ROOT.iterdir():
        if path.name in expected_entries:
            continue
        if path.is_symlink():
            raise SystemExit(f"Refusing to remove symlinked path: {path}")
        if path.resolve().parent != managed_root:
            raise SystemExit(f"Refusing to remove path outside {DESTINATION_ROOT}.")
        if path.is_dir():
            shutil.rmtree(path)
        else:
            path.unlink()

    for name, source in sources.items():
        destination = DESTINATION_ROOT / name
        if destination.is_symlink():
            raise SystemExit(f"Refusing to remove symlinked path: {destination}")
        if destination.exists():
            if destination.resolve().parent != managed_root:
                raise SystemExit(f"Refusing to remove path outside {DESTINATION_ROOT}.")
            shutil.rmtree(destination)
        shutil.copytree(source, destination)

    problems = differences()
    if problems:
        raise SystemExit("Plugin bundle still differs:\n" + "\n".join(problems))


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "--check", action="store_true", help="Check for drift without copying files."
    )
    args = parser.parse_args()

    if args.check:
        problems = differences()
        if problems:
            raise SystemExit("Plugin bundle differs:\n" + "\n".join(problems))
        print("Plugin skill bundle matches the canonical skills.")
        return

    sync()
    print("Plugin skill bundle updated from .agents/skills.")


if __name__ == "__main__":
    main()
