"""Copy the canonical project skills into the cross-runtime plugin bundle."""

from __future__ import annotations

import argparse
import filecmp
import shutil
from pathlib import Path


REPO_ROOT = Path(__file__).resolve().parents[1]
SOURCE_ROOT = REPO_ROOT / ".agents" / "skills"
DESTINATION_ROOT = REPO_ROOT / "plugins" / "fullstack-harness" / "skills"
MARKER = DESTINATION_ROOT / ".generated-from-agents-skills"
SKILL_NAMES = (
    "design-package-builder",
    "fullstack-harness-engineering",
    "prd-builder",
)


def included_files(root: Path) -> dict[Path, Path]:
    files: dict[Path, Path] = {}
    for path in root.rglob("*"):
        if not path.is_file():
            continue
        if "__pycache__" in path.parts or path.suffix == ".pyc":
            continue
        files[path.relative_to(root)] = path
    return files


def differences() -> list[str]:
    problems: list[str] = []
    for name in SKILL_NAMES:
        source = SOURCE_ROOT / name
        destination = DESTINATION_ROOT / name
        source_files = included_files(source)
        destination_files = included_files(destination) if destination.exists() else {}

        for relative in sorted(source_files.keys() - destination_files.keys()):
            problems.append(f"missing: {name}/{relative.as_posix()}")
        for relative in sorted(destination_files.keys() - source_files.keys()):
            problems.append(f"extra: {name}/{relative.as_posix()}")
        for relative in sorted(source_files.keys() & destination_files.keys()):
            if not filecmp.cmp(
                source_files[relative], destination_files[relative], shallow=False
            ):
                problems.append(f"changed: {name}/{relative.as_posix()}")
    return problems


def sync() -> None:
    if DESTINATION_ROOT.exists() and any(DESTINATION_ROOT.iterdir()) and not MARKER.exists():
        raise SystemExit(
            f"Refusing to overwrite unmanaged files under {DESTINATION_ROOT}."
        )

    DESTINATION_ROOT.mkdir(parents=True, exist_ok=True)
    MARKER.write_text(
        "Generated by scripts/sync_plugin_skills.py. "
        "Do not edit files in this directory directly.\n",
        encoding="utf-8",
    )
    for name in SKILL_NAMES:
        source = SOURCE_ROOT / name
        if not (source / "SKILL.md").is_file():
            raise SystemExit(f"Canonical skill is missing: {source}")
        shutil.copytree(source, DESTINATION_ROOT / name, dirs_exist_ok=True)

    problems = differences()
    if problems:
        raise SystemExit("Plugin bundle still differs:\n" + "\n".join(problems))


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "--check", action="store_true", help="Check for drift without copying files."
    )
    args = parser.parse_args()

    if args.check:
        problems = differences()
        if problems:
            raise SystemExit("Plugin bundle differs:\n" + "\n".join(problems))
        print("Plugin skill bundle matches the canonical skills.")
        return

    sync()
    print("Plugin skill bundle updated from .agents/skills.")


if __name__ == "__main__":
    main()
